teaapp/urls.py
from django.urls import path
from teaapp import views
from .views import *

app_name = "teaapp"

urlpatterns = [
    path('', tea_list, name='tea_list'),
    path('teas/add', tea_form, name='tea_form'),
    path('teas/<int:tea_id>/', tea_details, name='tea_details'),
    path('teas/<int:tea_id>/form/', tea_edit_form, name='tea_edit_form')
]

teashop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teaapp.urls'))
]

teaapp/models.py
from django.db import models

# Create your models here.

teaapp/models/packaging.py
from django.db import models
from django.urls import reverse


class Packaging(models.Model):

    name = models.CharField(max_length=100)
    handmade = models.BooleanField()
    production_location = models.CharField(max_length=100)
    teas = models.ManyToManyField("Tea", through='TeaPackaging')

    class Meta:
        verbose_name = ("Packaging")
        verbose_name_plural = ("Packagings")

    def __str__(self):
        return f"{self.name} ({self.flavor})"

    def get_absolute_url(self):
        return reverse("Packaging_detail", kwargs={"pk": self.pk})

teaapp/models/tea.py
from django.db import models
from django.urls import reverse


class Tea(models.Model):

    name = models.CharField(max_length=100)
    flavor = models.CharField(max_length=100)
    packagings = models.ManyToManyField("Packaging", through='TeaPackaging')

    class Meta:
        verbose_name = ("Tea")
        verbose_name_plural = ("Teas")

    def __str__(self):
        return f"{self.name} ({self.flavor})"

    def get_absolute_url(self):
        return reverse("Tea_detail", kwargs={"pk": self.pk})

teaapp/models/tea_packaging.py
from django.db import models


class TeaPackaging(models.Model):

    tea = models.ForeignKey("Tea", on_delete=models.CASCADE)
    packaging = models.ForeignKey("Packaging", on_delete=models.CASCADE)
    longevity_in_months = models.IntegerField()

teaapp/views.py
from django.shortcuts import render

# Create your views here.

teaapp/templates/home.html
{% extends 'shared/base.html' %}
{% block content %}
{% load static %}

<div class='content'>
<h1>I'm a list of teas!</h1>
<a href="{% url 'teaapp:tea_form' %}">Add a New Tea</a>

    {% for tea in teas %}

        <p>{{ tea.name }} - {{ tea.flavor }}</p>
        <a href="{% url 'teaapp:tea_details' tea.id %}">Details</a>
        
    {% endfor %}

<div>
{% endblock content %}

teaapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <title>Tea Shop</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" type="text/css" media="screen" />

    {% block css %}
    {% endblock %}

</head>

<body>
<img id='homeImage' src="{% static 'images/shop-illustration.jpg' %}"/>   
    {% block content %}
    {% endblock %}

    {% block scripts %}
    {% endblock scripts %}

</body>

</html>

teaapp/templates/teas/tea_details.html
{% extends 'shared/base.html' %}
{% block content %}
<div class='content'>
<h1>{{ tea.name }}</h1>
<h4>{{ tea.flavor }}</h4>

<h3>Available Packaging</h3>
{% for packaging in packaging_options %}
    <p>{{ packaging.name }}: Lasts {{ packaging.longevity_in_months }} months</p>
    <form action="{% url 'teaapp:tea_details' packaging.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="actual_method" value="DELETE">
    <button>Delete</button>
    </form>
{% endfor %}
<br><br>
    <form action="{% url 'teaapp:tea_edit_form' tea.id %}" method="GET">
    {% csrf_token %}
    <button>Edit</button>
    </form>
<!-- <a href="{% url 'teaapp:tea_edit_form' tea.id %}"><button>Edit</button></a> -->
<br><br>
<a href="{% url 'teaapp:tea_list' %}">Back</a>
</div>
{% endblock content %}

teaapp/templates/teas/tea_form.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
<div class='content'>
{% if tea.id is None %}
    <div class='form'>
    <form action="{% url 'teaapp:tea_list' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <label for="name">Name: </label>
            <input id="name" type="text" name="name">
        </fieldset>
        <fieldset>
            <label for="flavor">Flavor: </label>
            <input id="flavor" type="text" name="flavor">
        </fieldset>

        <!-- <fieldset>
        <label for="packaging">Assign to packaging: </label>
        <select id="packaging" type="text" name="packaging">
            {% for packaging in packaging_list %}
                <option value={{ packaging.id }}>{{ packaging }}</option>
            {% endfor %}
        </select>
        </fieldset> -->

        <input type="submit" value="Add Tea" />
    </form>
    </div>
{% elif tea.id is not None %}
    <div class='form'>
    <form action="{% url 'teaapp:tea_details' tea.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <label for="flavor">Flavor: </label>
            <input id="flavor" type="text" name="flavor" value="{{ tea.flavor }}">
        </fieldset>
        <input type="hidden" name="actual_method" value="PUT">
        <input type="submit" value="Update Flavor" />
    </form> 
    </div>  
{% endif %}
</div>
{% endblock content %}